### ISSUE TITLE
help with project

### ISSUE THREAD

**Issue by tariq421** [tariq421/MatchTheCards#2]
.....

**Comment by ajhofferber** [comment]
Hey Tariq,

When submitting an issue, you need to give us some more information! Issues need to explain clearly the blocker you are experiencing, and explain the steps you have taken to solve it. 

We would be glad to pair with you on a particular issue, but you need to pick one at a time that you are blocked on!

**Comment by rapala61** [comment]
Tariq, just as Ash mentioned, please follow the correct procedure to open an issue. Thanks.
